server:
  port: 9000
spring:
  application:
    name: demo-boot
  servlet:
    multipart:
      # 根据实际需求作调整
      # 默认最大上传文件大小为1M，单个文件大小
      max-file-size: 10MB
      # 默认最大请求大小为10M，总上传的数据大小
      max-request-size: 40MB


system:
  url:
    shouldSkipList:
      - "/test/*"
      - "/sso/token"
      - "/swagger-ui.html"
      - "/swagger-ui.html/**"
      - "/webjars/**"
      - "/swagger-resources/**"
      - "/v2/*"
      - "/"



